{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6236a79-221a-41bf-b59e-2fd691dbd13e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog, messagebox, ttk\n",
    "import os\n",
    "import threading\n",
    "import time\n",
    "import psutil\n",
    "from datetime import datetime, timedelta\n",
    "import random\n",
    "import numpy as np\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "class DriveScannerGUI:\n",
    "    def __init__(self, master):\n",
    "        self.master = master\n",
    "        self.master.title(\"🔍 Drive File Scanner\")\n",
    "        self.master.geometry(\"900x650\")\n",
    "        self.master.configure(bg=\"#1e1e2f\")\n",
    "\n",
    "        self.scanning = False\n",
    "        self.paused = False\n",
    "        self.stopped = False\n",
    "        self.total_files_scanned = 0\n",
    "        self.total_size_scanned = 0\n",
    "        self.start_time = None\n",
    "\n",
    "        self.create_widgets()\n",
    "        self.display_drive_info()\n",
    "\n",
    "    def create_widgets(self):\n",
    "        # Buttons Frame\n",
    "        btn_frame = tk.Frame(self.master, bg=\"#1e1e2f\")\n",
    "        btn_frame.pack(pady=10)\n",
    "\n",
    "        self.start_btn = tk.Button(btn_frame, text=\"Start Scan\", command=self.start_scan, bg=\"#28a745\", fg=\"white\", width=15)\n",
    "        self.start_btn.pack(side=tk.LEFT, padx=5)\n",
    "\n",
    "        self.pause_btn = tk.Button(btn_frame, text=\"Pause\", command=self.toggle_pause, bg=\"#ffc107\", fg=\"black\", width=15)\n",
    "        self.pause_btn.pack(side=tk.LEFT, padx=5)\n",
    "\n",
    "        self.stop_btn = tk.Button(btn_frame, text=\"Stop\", command=self.stop_scan, bg=\"#dc3545\", fg=\"white\", width=15)\n",
    "        self.stop_btn.pack(side=tk.LEFT, padx=5)\n",
    "\n",
    "        self.export_btn = tk.Button(btn_frame, text=\"Export Results\", command=self.export_results, bg=\"#007bff\", fg=\"white\", width=15)\n",
    "        self.export_btn.pack(side=tk.LEFT, padx=5)\n",
    "\n",
    "        # File Type Filter Dropdown\n",
    "        filter_frame = tk.Frame(self.master, bg=\"#1e1e2f\")\n",
    "        filter_frame.pack(pady=5)\n",
    "        tk.Label(filter_frame, text=\"Filter file type:\", bg=\"#1e1e2f\", fg=\"#00ffcc\").pack(side=tk.LEFT)\n",
    "        self.filetype_var = tk.StringVar(value=\"All files (*)\")\n",
    "        self.filetype_dropdown = ttk.Combobox(filter_frame, textvariable=self.filetype_var, width=20, state=\"readonly\")\n",
    "        self.filetype_dropdown['values'] = (\"All files (*)\", \"*.txt\", \"*.py\", \"*.jpg\", \"*.png\", \"*.exe\")\n",
    "        self.filetype_dropdown.pack(side=tk.LEFT, padx=5)\n",
    "\n",
    "        # Drive Info Label\n",
    "        self.drive_info = tk.Label(self.master, text=\"\", bg='#1e1e2f', fg='#00ffcc', font=(\"Segoe UI\", 10), justify=tk.LEFT)\n",
    "        self.drive_info.pack(pady=5, fill=tk.X, padx=10)\n",
    "\n",
    "        # Forecast Info Label\n",
    "        self.forecast_info = tk.Label(self.master, text=\"\", bg='#1e1e2f', fg='#ffaa00', font=(\"Segoe UI\", 9, \"italic\"), justify=tk.LEFT)\n",
    "        self.forecast_info.pack(pady=3, fill=tk.X, padx=10)\n",
    "\n",
    "        # Results Text Box with Scrollbar\n",
    "        text_frame = tk.Frame(self.master)\n",
    "        text_frame.pack(padx=10, pady=10, fill=tk.BOTH, expand=True)\n",
    "\n",
    "        self.text_box = tk.Text(text_frame, wrap=\"none\", height=20, bg=\"#262638\", fg=\"#00ff00\")\n",
    "        self.text_box.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)\n",
    "\n",
    "        scrollbar = tk.Scrollbar(text_frame, command=self.text_box.yview)\n",
    "        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)\n",
    "        self.text_box.config(yscrollcommand=scrollbar.set)\n",
    "\n",
    "        # Progress Bar\n",
    "        self.progress = ttk.Progressbar(self.master, orient=tk.HORIZONTAL, length=700, mode='determinate')\n",
    "        self.progress.pack(pady=5)\n",
    "\n",
    "        # Estimated Time & Status\n",
    "        self.status_label = tk.Label(self.master, text=\"\", bg='#1e1e2f', fg='#ffffff')\n",
    "        self.status_label.pack(pady=5)\n",
    "\n",
    "        self.eta_label = tk.Label(self.master, text=\"\", bg='#1e1e2f', fg='#aaaaaa')\n",
    "        self.eta_label.pack()\n",
    "\n",
    "        self.summary_label = tk.Label(self.master, text=\"\", bg='#1e1e2f', fg='#00ffcc', font=(\"Segoe UI\", 11, 'bold'))\n",
    "        self.summary_label.pack(pady=5)\n",
    "\n",
    "    def display_drive_info(self):\n",
    "        info = \"\"\n",
    "        for part in psutil.disk_partitions(all=False):\n",
    "            try:\n",
    "                usage = psutil.disk_usage(part.mountpoint)\n",
    "                info += f\"Drive {part.device} - Total: {self.convert_size(usage.total)}, Used: {self.convert_size(usage.used)}, Free: {self.convert_size(usage.free)}\\n\"\n",
    "            except Exception:\n",
    "                continue\n",
    "        self.drive_info.config(text=info)\n",
    "        self.drive_usage_forecasting()\n",
    "\n",
    "    def convert_size(self, size_bytes):\n",
    "        for unit in ['B', 'KB', 'MB', 'GB', 'TB']:\n",
    "            if size_bytes < 1024:\n",
    "                return f\"{size_bytes:.2f} {unit}\"\n",
    "            size_bytes /= 1024\n",
    "        return f\"{size_bytes:.2f} PB\"\n",
    "\n",
    "    def start_scan(self):\n",
    "        if not self.scanning:\n",
    "            path = filedialog.askdirectory(title=\"Select Folder to Scan\")\n",
    "            if path:\n",
    "                self.scanning = True\n",
    "                self.paused = False\n",
    "                self.stopped = False\n",
    "                self.total_files_scanned = 0\n",
    "                self.total_size_scanned = 0\n",
    "                self.start_time = time.time()\n",
    "                self.text_box.delete(1.0, tk.END)\n",
    "                self.summary_label.config(text=\"\")\n",
    "                self.progress['value'] = 0\n",
    "                threading.Thread(target=self.scan_directory, args=(path,), daemon=True).start()\n",
    "\n",
    "    def toggle_pause(self):\n",
    "        if self.scanning:\n",
    "            self.paused = not self.paused\n",
    "            self.pause_btn.config(text=\"Resume\" if self.paused else \"Pause\")\n",
    "            self.status_label.config(text=\"⏸️ Paused\" if self.paused else \"▶️ Resumed\")\n",
    "\n",
    "    def stop_scan(self):\n",
    "        if self.scanning:\n",
    "            self.stopped = True\n",
    "            self.scanning = False\n",
    "            self.paused = False\n",
    "            self.pause_btn.config(text=\"Pause\")\n",
    "            self.status_label.config(text=\"🛑 Scan Stopped by User\")\n",
    "\n",
    "    def scan_directory(self, path):\n",
    "        # Count total files first for progress bar\n",
    "        total_files = 0\n",
    "        for root, dirs, files in os.walk(path):\n",
    "            total_files += len(files)\n",
    "        if total_files == 0:\n",
    "            self.status_label.config(text=\"No files found in selected folder.\")\n",
    "            self.scanning = False\n",
    "            return\n",
    "\n",
    "        self.progress['maximum'] = total_files\n",
    "\n",
    "        filter_type = self.filetype_var.get()\n",
    "        # Convert filter to usable format\n",
    "        filter_pattern = None\n",
    "        if filter_type != \"All files (*)\":\n",
    "            filter_pattern = filter_type.lstrip(\"*\")\n",
    "\n",
    "        for root, dirs, files in os.walk(path):\n",
    "            while self.paused:\n",
    "                time.sleep(0.5)\n",
    "                self.status_label.config(text=\"⏸️ Paused\")\n",
    "\n",
    "            if self.stopped:\n",
    "                break\n",
    "\n",
    "            for file in files:\n",
    "                if self.stopped:\n",
    "                    break\n",
    "\n",
    "                # File type filter check\n",
    "                if filter_pattern and not file.endswith(filter_pattern):\n",
    "                    continue\n",
    "\n",
    "                try:\n",
    "                    full_path = os.path.join(root, file)\n",
    "\n",
    "                    # Access checks\n",
    "                    is_readable = os.access(full_path, os.R_OK)\n",
    "                    is_writable = os.access(full_path, os.W_OK)\n",
    "                    is_executable = os.access(full_path, os.X_OK)\n",
    "\n",
    "                    access_info = []\n",
    "                    if is_readable:\n",
    "                        access_info.append(\"Read\")\n",
    "                    if is_writable:\n",
    "                        access_info.append(\"Write\")\n",
    "                    if is_executable:\n",
    "                        access_info.append(\"Execute\")\n",
    "\n",
    "                    access_str = \", \".join(access_info) if access_info else \"No Access\"\n",
    "\n",
    "                    file_size = os.path.getsize(full_path)\n",
    "                    self.total_size_scanned += file_size\n",
    "\n",
    "                    # --- File Anomaly & Risk Detection ---\n",
    "                    risk_flag = self.check_risk(full_path, file, file_size)\n",
    "\n",
    "                    display_line = f\"{full_path} [Size: {self.convert_size(file_size)} | Access: {access_str}]\"\n",
    "                    if risk_flag:\n",
    "                        display_line += \" [⚠️ RISKY]\"\n",
    "\n",
    "                    self.text_box.insert(tk.END, display_line + \"\\n\")\n",
    "                    self.total_files_scanned += 1\n",
    "                    self.update_status(total_files)\n",
    "                    self.text_box.see(tk.END)\n",
    "                except Exception as e:\n",
    "                    self.text_box.insert(tk.END, f\"{full_path} [Error: {e}]\\n\")\n",
    "                    continue\n",
    "\n",
    "        self.scanning = False\n",
    "        if not self.stopped:\n",
    "            self.status_label.config(text=\"✅ Scan Complete\")\n",
    "            self.eta_label.config(text=\"\")\n",
    "            elapsed_time = time.time() - self.start_time\n",
    "            summary_text = (f\"Total Files Scanned: {self.total_files_scanned}\\n\"\n",
    "                            f\"Total Size Scanned: {self.convert_size(self.total_size_scanned)}\\n\"\n",
    "                            f\"Elapsed Time: {elapsed_time:.2f} seconds\")\n",
    "            self.summary_label.config(text=summary_text)\n",
    "        else:\n",
    "            self.status_label.config(text=\"🛑 Scan Stopped\")\n",
    "            self.eta_label.config(text=\"\")\n",
    "            self.summary_label.config(text=\"\")\n",
    "\n",
    "    def update_status(self, total_files):\n",
    "        self.progress['value'] = self.total_files_scanned\n",
    "        elapsed = time.time() - self.start_time\n",
    "        if self.total_files_scanned > 0 and elapsed > 0:\n",
    "            rate = self.total_files_scanned / elapsed\n",
    "            remaining = total_files - self.total_files_scanned\n",
    "            eta_seconds = remaining / rate\n",
    "            eta_str = str(timedelta(seconds=int(eta_seconds)))\n",
    "            self.eta_label.config(text=f\"Estimated time remaining: {eta_str}\")\n",
    "        self.status_label.config(text=f\"Scanning... {self.total_files_scanned}/{total_files} files\")\n",
    "\n",
    "    def check_risk(self, full_path, file_name, file_size):\n",
    "        # Simple heuristic examples for anomaly detection:\n",
    "\n",
    "        # 1. Large executable files (e.g., > 50 MB)\n",
    "        if file_name.endswith('.exe') and file_size > 50 * 1024 * 1024:\n",
    "            return True\n",
    "\n",
    "        # 2. Files with suspicious extensions or double extensions (e.g., \".txt.exe\")\n",
    "        if \".txt.exe\" in file_name.lower():\n",
    "            return True\n",
    "\n",
    "        # 3. Hidden files (starts with .) with executable permission\n",
    "        if file_name.startswith('.') and os.access(full_path, os.X_OK):\n",
    "            return True\n",
    "\n",
    "        # 4. Recently modified files that are large (e.g., > 100MB in last 1 day)\n",
    "        try:\n",
    "            mtime = os.path.getmtime(full_path)\n",
    "            if file_size > 100 * 1024 * 1024 and (time.time() - mtime) < 86400:\n",
    "                return True\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "        return False\n",
    "\n",
    "    def export_results(self):\n",
    "        if self.total_files_scanned == 0:\n",
    "            messagebox.showinfo(\"Export Results\", \"No scan results to export.\")\n",
    "            return\n",
    "        export_path = filedialog.asksaveasfilename(defaultextension=\".txt\",\n",
    "                                                   filetypes=[(\"Text files\", \"*.txt\"), (\"All files\", \"*.*\")],\n",
    "                                                   title=\"Save Scan Results\")\n",
    "        if export_path:\n",
    "            try:\n",
    "                with open(export_path, 'w', encoding='utf-8') as f:\n",
    "                    f.write(self.text_box.get(1.0, tk.END))\n",
    "                messagebox.showinfo(\"Export Results\", f\"Results exported successfully to:\\n{export_path}\")\n",
    "            except Exception as e:\n",
    "                messagebox.showerror(\"Export Results\", f\"Failed to export results:\\n{e}\")\n",
    "\n",
    "    def drive_usage_forecasting(self):\n",
    "        # Forecast disk usage increase over next 7 days using simple linear regression on past week data\n",
    "\n",
    "        try:\n",
    "            # Simulate past 7 days usage data in bytes\n",
    "            # In real scenario, you'd get actual historical usage (e.g. saved daily)\n",
    "            # Here, we create random data to simulate growth trend\n",
    "\n",
    "            total, used, free = 0, 0, 0\n",
    "            for part in psutil.disk_partitions(all=False):\n",
    "                try:\n",
    "                    usage = psutil.disk_usage(part.mountpoint)\n",
    "                    total += usage.total\n",
    "                    used += usage.used\n",
    "                    free += usage.free\n",
    "                except Exception:\n",
    "                    continue\n",
    "\n",
    "            today_used = used\n",
    "            # Create synthetic data: usage over past 7 days (in GB)\n",
    "            # Let's say usage was slightly increasing daily, simulate with noise\n",
    "            days = np.arange(7).reshape(-1, 1)\n",
    "            base_usage = (today_used - 7*500*1024*1024) / (1024**3)  # baseline usage 7 days ago (subtract 500MB daily approx)\n",
    "            usage_values = base_usage + 0.5 * days.flatten() + np.random.normal(0, 0.1, size=7)\n",
    "            usage_values = np.maximum(usage_values, 0)\n",
    "\n",
    "            # Fit linear regression\n",
    "            model = LinearRegression()\n",
    "            model.fit(days, usage_values)\n",
    "\n",
    "            # Predict usage next 7 days\n",
    "            future_days = np.arange(7, 14).reshape(-1, 1)\n",
    "            forecast = model.predict(future_days)\n",
    "\n",
    "            # Prepare forecast summary\n",
    "            forecast_text = \"📊 Disk Usage Forecast (Next 7 days):\\n\"\n",
    "            for i, val in enumerate(forecast):\n",
    "                day = (datetime.now() + timedelta(days=i+1)).strftime(\"%a %b %d\")\n",
    "                forecast_text += f\"  {day}: {val:.2f} GB used\\n\"\n",
    "\n",
    "            self.forecast_info.config(text=forecast_text)\n",
    "\n",
    "        except Exception as e:\n",
    "            self.forecast_info.config(text=f\"Forecast unavailable: {e}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = DriveScannerGUI(root)\n",
    "    root.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
